# Usa a versão Alpine por ser mais leve
FROM node:20-alpine

# Define o diretório de trabalho
WORKDIR /usr/src/app

# Copia apenas os arquivos de dependências primeiro (otimiza o cache do Docker)
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante dos arquivos do front
COPY . .

# Expõe a porta padrão do React/Vite/Next
EXPOSE 3000

# Comando para iniciar
CMD ["npm", "start"]