listening-port=3478

min-port=49160
max-port=49200

fingerprint


use-auth-secret

static-auth-secret=aB7vP2mX9qRw8KzLd4YnU1HsCf6JtG5WpNe3MxQa8VrBi0FuTk7DsLpXc2HvZm91

realm=therapistfriend.local

stale-nonce

total-quota=100
bps-capacity=0

no-multicast-peers

log-file=stdout
simple-log