# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import analisador_pb2 as analisador__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in analisador_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalisadorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectEmotion = channel.unary_unary(
                '/emotion.AnalisadorService/DetectEmotion',
                request_serializer=analisador__pb2.FrameRequest.SerializeToString,
                response_deserializer=analisador__pb2.FrameResponse.FromString,
                _registered_method=True)
        self.ObterResumoConsolidado = channel.unary_unary(
                '/emotion.AnalisadorService/ObterResumoConsolidado',
                request_serializer=analisador__pb2.ResumoRequest.SerializeToString,
                response_deserializer=analisador__pb2.ResumoResponse.FromString,
                _registered_method=True)


class AnalisadorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectEmotion(self, request, context):
        """Chamado durante a call (Real-time)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterResumoConsolidado(self, request, context):
        """Chamado pelo Worker via BullMQ (Background)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalisadorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectEmotion': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectEmotion,
                    request_deserializer=analisador__pb2.FrameRequest.FromString,
                    response_serializer=analisador__pb2.FrameResponse.SerializeToString,
            ),
            'ObterResumoConsolidado': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterResumoConsolidado,
                    request_deserializer=analisador__pb2.ResumoRequest.FromString,
                    response_serializer=analisador__pb2.ResumoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'emotion.AnalisadorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('emotion.AnalisadorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalisadorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectEmotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emotion.AnalisadorService/DetectEmotion',
            analisador__pb2.FrameRequest.SerializeToString,
            analisador__pb2.FrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObterResumoConsolidado(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emotion.AnalisadorService/ObterResumoConsolidado',
            analisador__pb2.ResumoRequest.SerializeToString,
            analisador__pb2.ResumoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
