# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analisador.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analisador.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61nalisador.proto\x12\x07\x65motion\"0\n\x0c\x46rameRequest\x12\x10\n\x08sessaoId\x18\x01 \x01(\t\x12\x0e\n\x06imagem\x18\x02 \x01(\x0c\"2\n\rFrameResponse\x12\x0e\n\x06\x65mocao\x18\x01 \x01(\t\x12\x11\n\tconfianca\x18\x02 \x01(\x02\"!\n\rResumoRequest\x12\x10\n\x08sessaoId\x18\x01 \x01(\t\"W\n\x0eResumoResponse\x12\x17\n\x0f\x65mocaoDominante\x18\x01 \x01(\t\x12\x16\n\x0epicosAnsiedade\x18\x02 \x01(\x05\x12\x14\n\x0cjsonGraficos\x18\x03 \x01(\t2\x9e\x01\n\x11\x41nalisadorService\x12>\n\rDetectEmotion\x12\x15.emotion.FrameRequest\x1a\x16.emotion.FrameResponse\x12I\n\x16ObterResumoConsolidado\x12\x16.emotion.ResumoRequest\x1a\x17.emotion.ResumoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analisador_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEREQUEST']._serialized_start=29
  _globals['_FRAMEREQUEST']._serialized_end=77
  _globals['_FRAMERESPONSE']._serialized_start=79
  _globals['_FRAMERESPONSE']._serialized_end=129
  _globals['_RESUMOREQUEST']._serialized_start=131
  _globals['_RESUMOREQUEST']._serialized_end=164
  _globals['_RESUMORESPONSE']._serialized_start=166
  _globals['_RESUMORESPONSE']._serialized_end=253
  _globals['_ANALISADORSERVICE']._serialized_start=256
  _globals['_ANALISADORSERVICE']._serialized_end=414
# @@protoc_insertion_point(module_scope)
